import { describe, expect, it } from 'vitest';
import { GMAIL_QUERY, isBulkMail } from '@cairn/connectors';

/**
 * What the owner actually reported: "you're basically getting memory from
 * useless stuff on Gmail... I usually receive a lot of newsletters and things
 * that are nonsense." A connector that turns a mailbox into a review queue of
 * marketing copy is worse than one that is not connected at all.
 *
 * `mail-filter.test.ts` covers the judgement itself. These cover the two places
 * the Gmail connector applies it: the query it sends, and the predicate it runs
 * over each fetched message.
 */

const message = (labelIds: string[], headers: Record<string, string>) => ({
  labelIds,
  payload: {
    headers: Object.entries(headers).map(([name, value]) => ({ name, value })),
  },
});

describe('GMAIL_QUERY', () => {
  it('leaves sent mail unconditioned', () => {
    // The bug this pins: with the category exclusions spanning the whole query,
    // Gmail dropped any sent message it had categorised server-side, before the
    // connector saw it — so the "a person's own words are never discarded" rule
    // never ran. Anyone who mails their own newsletter lost everything they
    // wrote. Everything past the OR must stay bare.
    const [, sentArm] = GMAIL_QUERY.split(' OR ');
    expect(sentArm).toBe('in:sent');
  });

  it('excludes the bulk categories from the inbox arm', () => {
    const [inboxArm] = GMAIL_QUERY.split(' OR ');
    for (const category of ['promotions', 'social', 'forums']) {
      expect(inboxArm).toContain(`-category:${category}`);
    }
  });

  it('leaves Updates alone', () => {
    // Receipts, bookings and confirmations live there alongside the noise, and
    // the per-message header checks judge those better than a whole category
    // exclusion can.
    expect(GMAIL_QUERY).not.toContain('category:updates');
  });
});

describe('isBulkMail', () => {
  it('skips a newsletter', () => {
    // List-Unsubscribe is the strongest signal available: the RFC says these
    // fields are generated by mailing list software, never by a person.
    expect(
      isBulkMail(
        message(['INBOX'], {
          From: 'The Weekly <hello@theweekly.example>',
          Subject: 'Your Tuesday briefing',
          'List-Unsubscribe': '<https://theweekly.example/u/abc>',
        }),
      ),
    ).toBe(true);
  });

  it('keeps a plain human email', () => {
    expect(
      isBulkMail(
        message(['INBOX'], {
          From: 'Priya Anand <priya@example.com>',
          To: 'sam@example.com',
          Subject: 'Mill Street lease',
        }),
      ),
    ).toBe(false);
  });

  it('keeps a sent message even when it looks like bulk', () => {
    // Someone who mails their own newsletter would otherwise lose every message
    // they wrote. No header may overrule the SENT label.
    expect(
      isBulkMail(
        message(['SENT'], {
          From: 'newsletter@mine.example',
          'List-Unsubscribe': '<https://mine.example/u>',
          'List-Id': '<mine.example>',
          Precedence: 'bulk',
        }),
      ),
    ).toBe(false);
  });

  it('skips a noreply sender', () => {
    expect(isBulkMail(message(['INBOX'], { From: 'no-reply@bank.example' }))).toBe(true);
  });

  it('reads headers whatever case Gmail sends them in', () => {
    // Gmail returns headers as the sender wrote them, so the casing varies by
    // sender rather than by anything this code controls.
    expect(isBulkMail(message(['INBOX'], { from: 'NoReply@bank.example' }))).toBe(true);
    expect(isBulkMail(message(['INBOX'], { 'LIST-ID': '<a.example>' }))).toBe(true);
  });

  it('keeps a message with no headers at all rather than guessing', () => {
    expect(isBulkMail({ labelIds: ['INBOX'], payload: {} })).toBe(false);
    expect(isBulkMail({})).toBe(false);
  });
});
