import { describe, expect, it } from 'vitest';
import { GMAIL_QUERY, isExcludedMail } from '@cairn/connectors';

/**
 * What the owner actually reported, in two rounds. First: "you're basically
 * getting memory from useless stuff on Gmail... I usually receive a lot of
 * newsletters and things that are nonsense." Once bulk mail was excluded,
 * a parish's own attendance reminder still made it through — no bulk header
 * on it at all — and the owner's actual want turned out to be narrower than
 * "not obviously spam": "what I send to people and what I get back from
 * threads," full stop. `isExcludedMail` now defaults to exclusion; a message
 * has to be a reply, or something the person wrote, to survive at all.
 *
 * `mail-filter.test.ts` covers the judgement itself. These cover the two places
 * the Gmail connector applies it: the query it sends, and the predicate it runs
 * over each fetched message.
 */

const message = (labelIds: string[], headers: Record<string, string>) => ({
  labelIds,
  payload: {
    headers: Object.entries(headers).map(([name, value]) => ({ name, value })),
  },
});

/** Everything but a SENT message needs this to reach the check it is testing. */
const REPLY = { 'In-Reply-To': '<earlier-message@example.com>' };

describe('GMAIL_QUERY', () => {
  it('leaves sent mail unconditioned', () => {
    // The bug this pins: with the category exclusions spanning the whole query,
    // Gmail dropped any sent message it had categorised server-side, before the
    // connector saw it — so the "a person's own words are never discarded" rule
    // never ran. Anyone who mails their own newsletter lost everything they
    // wrote. Everything past the OR must stay bare.
    const [, sentArm] = GMAIL_QUERY.split(' OR ');
    expect(sentArm).toBe('in:sent');
  });

  it('excludes the bulk categories from the inbox arm', () => {
    const [inboxArm] = GMAIL_QUERY.split(' OR ');
    for (const category of ['promotions', 'social', 'forums']) {
      expect(inboxArm).toContain(`-category:${category}`);
    }
  });

  it('leaves Updates alone', () => {
    // Receipts, bookings and confirmations live there alongside the noise, and
    // the per-message header checks — including the reply gate, which most of
    // what lives in Updates will simply fail — judge those better than a whole
    // category exclusion can.
    expect(GMAIL_QUERY).not.toContain('category:updates');
  });
});

describe('isExcludedMail', () => {
  it('excludes a message that is not a reply, however ordinary it looks', () => {
    // The gate itself, at the connector level. Nothing here is bulk mail by any
    // signal Gmail or a header would offer — this is what a real person's
    // unanswered first message looks like from the outside, indistinguishable
    // without a reply header from cold mail or a one-off automated notice.
    expect(
      isExcludedMail(
        message(['INBOX'], {
          From: 'Priya Anand <priya@example.com>',
          To: 'sam@example.com',
          Subject: 'Mill Street lease',
        }),
      ),
    ).toBe(true);
  });

  it('keeps a reply from a real person', () => {
    expect(
      isExcludedMail(
        message(['INBOX'], {
          From: 'Priya Anand <priya@example.com>',
          To: 'sam@example.com',
          Subject: 'Re: Mill Street lease',
          ...REPLY,
        }),
      ),
    ).toBe(false);
  });

  it('skips a newsletter even mid-thread', () => {
    // List-Unsubscribe is the strongest signal available: the RFC says these
    // fields are generated by mailing list software, never by a person. The
    // reply header here stands in for a drip campaign threaded to look like an
    // ongoing conversation — the reply gate alone would not catch this.
    expect(
      isExcludedMail(
        message(['INBOX'], {
          From: 'The Weekly <hello@theweekly.example>',
          Subject: 'Your Tuesday briefing',
          'List-Unsubscribe': '<https://theweekly.example/u/abc>',
          ...REPLY,
        }),
      ),
    ).toBe(true);
  });

  it('keeps a sent message even when it looks like bulk, reply or not', () => {
    // Someone who mails their own newsletter would otherwise lose every message
    // they wrote. No header may overrule the SENT label, and unlike everything
    // else here, a sent message needs no reply header at all.
    expect(
      isExcludedMail(
        message(['SENT'], {
          From: 'newsletter@mine.example',
          'List-Unsubscribe': '<https://mine.example/u>',
          'List-Id': '<mine.example>',
          Precedence: 'bulk',
        }),
      ),
    ).toBe(false);
  });

  it('skips a noreply sender mid-thread', () => {
    expect(isExcludedMail(message(['INBOX'], { From: 'no-reply@bank.example', ...REPLY }))).toBe(
      true,
    );
  });

  it('reads headers whatever case Gmail sends them in', () => {
    // Gmail returns headers as the sender wrote them, so the casing varies by
    // sender rather than by anything this code controls. Lower-cased here
    // deliberately, since the reply header itself is asserted title-cased above.
    expect(
      isExcludedMail(message(['INBOX'], { from: 'NoReply@bank.example', 'in-reply-to': '<x>' })),
    ).toBe(true);
    expect(
      isExcludedMail(message(['INBOX'], { 'LIST-ID': '<a.example>', 'IN-REPLY-TO': '<x>' })),
    ).toBe(true);
  });

  it('excludes a message with no headers at all, rather than guessing it belongs', () => {
    // The default flipped: nothing here is proof of anything bulk, but nothing
    // here is proof of correspondence either, and the second is now what is
    // required. A missing header used to mean "keep, absent evidence of spam";
    // it now means "exclude, absent evidence of a reply."
    expect(isExcludedMail({ labelIds: ['INBOX'], payload: {} })).toBe(true);
    expect(isExcludedMail({})).toBe(true);
  });

  it('keeps a sent message with no headers at all', () => {
    // The one exception: SENT never needed a reply header, before or after the
    // default flipped.
    expect(isExcludedMail({ labelIds: ['SENT'], payload: {} })).toBe(false);
  });
});
